### ISSUE TITLE
make public

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.meta.report.data.creator#2]
defaulting to private repo, but I don't think there's anything in here that can't be public.

**Comment by cjyetman** [comment]
I've reviewed all the files in this repo and I don't see anything project specific, proprietary, or necessarily secret, so I'm going to go ahead and make this public.

**Comment by cjyetman** [comment]
oops, I don't have admin privilege to make public, so re-opening...

@AlexAxthelm I give my 👍🏻 for making public
